# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefa.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tarefa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctarefa.proto\x12\x07tarefas\"r\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x0e\n\x06\x65stado\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x61ta_criacao\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x61ta_limite\x18\x06 \x01(\t\".\n\nTarefaList\x12 \n\x07tarefas\x18\x01 \x03(\x0b\x32\x0f.tarefas.Tarefa\"\x07\n\x05\x45mpty2\xb3\x01\n\rTarefaService\x12\x34\n\rListarTarefas\x12\x0e.tarefas.Empty\x1a\x13.tarefas.TarefaList\x12/\n\x0b\x43riarTarefa\x12\x0f.tarefas.Tarefa\x1a\x0f.tarefas.Tarefa\x12;\n\x11\x43riarTarefaStream\x12\x0f.tarefas.Tarefa\x1a\x13.tarefas.TarefaList(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAREFA']._serialized_start=25
  _globals['_TAREFA']._serialized_end=139
  _globals['_TAREFALIST']._serialized_start=141
  _globals['_TAREFALIST']._serialized_end=187
  _globals['_EMPTY']._serialized_start=189
  _globals['_EMPTY']._serialized_end=196
  _globals['_TAREFASERVICE']._serialized_start=199
  _globals['_TAREFASERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
