version: '3.8'

services:
  rest:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 rest/app.py
    ports:
      - "8001:8001"
    volumes:
      - ./server/dados:/app/dados

  soap:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 soap/app.py
    ports:
      - "8002:8002"
    volumes:
      - ./server/dados:/app/dados

  graphql:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 graphql/app.py
    ports:
      - "8003:8003"
    volumes:
      - ./server/dados:/app/dados

  grpc:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 grpc/app.py
    ports:
      - "5001:5001"
    volumes:
      - ./server/dados:/app/dados

  cliente:
    build:
      context: ./cliente
      dockerfile: ../server/Dockerfile  # Usa o mesmo Dockerfile que os outros
    command: python3 app.py
    depends_on:
      - rest
      - soap
      - graphql
      - grpc
    stdin_open: true
    tty: true

