services:
  rest:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server/dados:/dados

  soap:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - dados_tarefas:/dados
    ports:
      - "8000:8000"

  graphql:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - dados_tarefas:/dados
    ports:
      - "4000:4000"

  grpc:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - dados_tarefas:/dados
    ports:
      - "50051:50051"

  cliente:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - rest
      - soap
      - graphql
      - grpc
    stdin_open: true
    tty: true

volumes:
  dados_tarefas:
