services:
  rest:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 rest/app.py
    ports:
      - "5000:5000"
    volumes:
      - ./server/dados:/dados
      - ./server:/server

  soap:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 soap/app.py
    volumes:
      - ./server/dados:/dados
    ports:
      - "8000:8000"

  graphql:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 graphql/app.py
    volumes:
      - ./server/dados:/dados
      - ./server:/server
    ports:
      - "4000:4000"

  grpc:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 grpc/app.py
    volumes:
      - ./server/dados:/dados
    ports:
      - "50051:50051"

  cliente:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 cliente/app.py
    depends_on:
      - rest
      - soap
      - graphql
      - grpc
    stdin_open: true
    tty: true
