version: '3.8'

services:
  servidor:
    build:
      context: ./servidor
    ports:
      - "5000:5000"
    volumes:
      - ./servidor/data:/app/data
    networks:
      - chat-network

  cliente:
    build:
      context: ./cliente
    depends_on:
      - servidor
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
