FROM python:3.10
WORKDIR /app
COPY services/rest_service.py .
COPY data/data.json /app/data/data.json
RUN pip install fastapi uvicorn pydantic
CMD ["uvicorn", "rest_service:app", "--host", "0.0.0.0", "--port", "8002"]
